# <u> Use only those concepts which have been taught till now </u>

In [ ]:
import numpy as np

# <u>**Problem 1**</u>

### What is the average value of the first 5 rows of the third and fourth columns?



In [ ]:
np.random.seed(21) # This guarantees the code will generate the same set of random numbers whenever executed
random_integers = np.random.randint(1,high=500000, size=(20, 5))
random_integers

array([[ 80842, 333008, 202553, 140037,  81969],
       [ 63857,  42105, 261540, 481981, 176739],
       [489984, 326386, 110795, 394863,  25024],
       [ 38317,  49982, 408830, 485118,  16119],
       [407675, 231729, 265455, 109413, 103399],
       [174677, 343356, 301717, 224120, 401101],
       [140473, 254634, 112262,  25063, 108262],
       [375059, 406983, 208947, 115641, 296685],
       [444899, 129585, 171318, 313094, 425041],
       [188411, 335140, 141681,  59641, 211420],
       [287650,   8973, 477425, 382803, 465168],
       [  3975,  32213, 160603, 275485, 388234],
       [246225,  56174, 244097,   9350, 496966],
       [225516, 273338,  73335, 283013, 212813],
       [ 38175, 282399, 318413, 337639, 379802],
       [198049, 101115, 419547, 260219, 325793],
       [148593, 425024, 348570, 117968, 107007],
       [ 52547, 180346, 178760, 305186, 262153],
       [ 11835, 449971, 494184, 472031, 353049],
       [476442,  35455, 191553, 384154,  29917]])

In [ ]:
# Your code here
sum=np.sum(random_integers[0:5,2:4])
count=np.count_nonzero(random_integers[0:5,2:4])
average=sum/count
print(average)

286058.5


#<u>**Problem 2**</u>

### In this problem, we are going to calculate distances between some pairs of points :

### <u> Measures of distances </u>
* ### Euclidean Distance : The distance between two points $(x_{1},y_{1})$ , $(x_{2},y_{2})$ is defined as :
${\displaystyle d(x,y)={\sqrt {(x_{1}-x_{2})^{2}+(y_{1}-y_{2})^{2}}}.}$

* ### Manhattan Distance : The distance between two points $(x_{1},y_{1})$ , $(x_{2},y_{2})$ is defined as :
${\displaystyle d(x,y)=|x_{1}-x_{2}|+|y_{1}-y_{2}|}$


### Create a 2-D array of 10 points where the x-coordinates and the y-coordinates can take random integral values between 5 and 20.


### Next, create two 1-D arrays(one for  Euclidean distance and the other for  Manhattan distance) for these points


In [ ]:
# Create the 10 points
pointes= np.array(np.random.randint(5,20,(10,2)))
pointes

array([[ 5, 10],
       [ 7, 10],
       [ 8, 13],
       [14, 16],
       [19,  8],
       [13, 12],
       [ 6, 17],
       [19, 16],
       [15, 11],
       [11, 16]])

In [ ]:
# Calculate Euclidean distances between these pairs of points (total 10*10 = 100 pairs including self pairs). This should give you a 10*10 2-D array where each value corresponds to the distance between a pair
def euc_dis(point1,point2):
  x1,y1=point1
  x2,y2=point2
  return round(((x2-x1)**2+(y2-y1)**2)**0.5,2)
euc_dis_list=[]
for i in range(10):
  inline=[]
  for j in range(10):
    inline.append(euc_dis(pointes[i],pointes[j]))
  euc_dis_list.append(np.asarray(inline))
euc_dis_list=np.asarray(euc_dis_list)
print(euc_dis_list)





[[ 0.    2.    4.24 10.82 14.14  8.25  7.07 15.23 10.05  8.49]
 [ 2.    0.    3.16  9.22 12.17  6.32  7.07 13.42  8.06  7.21]
 [ 4.24  3.16  0.    6.71 12.08  5.1   4.47 11.4   7.28  4.24]
 [10.82  9.22  6.71  0.    9.43  4.12  8.06  5.    5.1   3.  ]
 [14.14 12.17 12.08  9.43  0.    7.21 15.81  8.    5.   11.31]
 [ 8.25  6.32  5.1   4.12  7.21  0.    8.6   7.21  2.24  4.47]
 [ 7.07  7.07  4.47  8.06 15.81  8.6   0.   13.04 10.82  5.1 ]
 [15.23 13.42 11.4   5.    8.    7.21 13.04  0.    6.4   8.  ]
 [10.05  8.06  7.28  5.1   5.    2.24 10.82  6.4   0.    6.4 ]
 [ 8.49  7.21  4.24  3.   11.31  4.47  5.1   8.    6.4   0.  ]]


In [ ]:
# Calculate Manhattan distances between these pairs of points (total 10*10 = 100 pairs inlcuding self pairs).This should give you a 10*10 2-D array where each value corresponds to the distance between a pair.
def man_dis(point1,point2):
  x1,y1=point1
  x2,y2=point2
  return round((abs(x2-x1)+abs(y2-y1)),2)
man_dis_list=[]
for i in range(10):
  inline=[]
  for j in range(10):
    inline.append(man_dis(pointes[i],pointes[j]))
  man_dis_list.append(np.asarray(inline))
man_dis_list=np.asarray(man_dis_list)
print(man_dis_list)




[[ 0  2  6 15 16 10  8 20 11 12]
 [ 2  0  4 13 14  8  8 18  9 10]
 [ 6  4  0  9 16  6  6 14  9  6]
 [15 13  9  0 13  5  9  5  6  3]
 [16 14 16 13  0 10 22  8  7 16]
 [10  8  6  5 10  0 12 10  3  6]
 [ 8  8  6  9 22 12  0 14 15  6]
 [20 18 14  5  8 10 14  0  9  8]
 [11  9  9  6  7  3 15  9  0  9]
 [12 10  6  3 16  6  6  8  9  0]]


## Find the closest pairs (excluding self pairs) on the basis of both the distance measures

In [ ]:
# Your code here
nearest_points_manhattan=[]
for ind,arr in enumerate(man_dis_list+np.identity(10)*1000):
    nearest_points_manhattan.append((pointes[ind],pointes[arr.argmin()]))         # index of the value with min distance is stored and the corrosponding points accesed
    
print(nearest_points_manhattan)

nearest_points_euc=[]
for ind,arr in enumerate(euc_dis_list+np.identity(10)*1000):
    nearest_points_euc.append((pointes[ind],pointes[arr.argmin()]))         # index of the value with min distance is stored and the corrosponding points accesed
    
print(nearest_points_euc)




[(array([ 5, 10]), array([ 7, 10])), (array([ 7, 10]), array([ 5, 10])), (array([ 8, 13]), array([ 7, 10])), (array([14, 16]), array([11, 16])), (array([19,  8]), array([15, 11])), (array([13, 12]), array([15, 11])), (array([ 6, 17]), array([ 8, 13])), (array([19, 16]), array([14, 16])), (array([15, 11]), array([13, 12])), (array([11, 16]), array([14, 16]))]
[(array([ 5, 10]), array([ 7, 10])), (array([ 7, 10]), array([ 5, 10])), (array([ 8, 13]), array([ 7, 10])), (array([14, 16]), array([11, 16])), (array([19,  8]), array([15, 11])), (array([13, 12]), array([15, 11])), (array([ 6, 17]), array([ 8, 13])), (array([19, 16]), array([14, 16])), (array([15, 11]), array([13, 12])), (array([11, 16]), array([14, 16]))]


# <u>**Problem 3**</u>

## Extract all the contiguous 3x3 blocks from a random 10x10 matrix. For example, the first matrix corresponds to [:3,:3], then the second matrix corresponds to [:3,1:4],.... Once you have covered the first three rows, then the next set of matrices would be [1:4,:3],[1:4,1:4],.... and so on and so forth. The last matrix would be [7:10,7:10]

In [ ]:
# Your code below ..
random_3D_cohort =np.random.randint(10,50,(10,10))
print(random_3D_cohort)
ppp=[]
# for i,j in enumerate(random_3D_cohort):
for row in range(0,8):
  for col in range(0,8):
    ppp.append(random_3D_cohort[row:row+3,col:col+3])
pppa=np.asarray(ppp)
print(pppa)


# random_3D_cohort[:3,:3]





[[17 14 28 18 44 32 33 11 43 49]
 [40 42 26 10 25 19 17 37 41 33]
 [35 42 13 23 18 41 23 18 37 39]
 [43 44 42 34 27 17 47 11 17 13]
 [19 23 35 19 40 17 27 29 10 39]
 [40 24 40 31 13 41 35 41 22 10]
 [45 11 22 39 30 13 36 20 49 47]
 [43 49 13 13 40 41 47 11 38 26]
 [22 30 28 30 35 15 31 33 38 28]
 [16 26 17 32 34 21 27 34 37 12]]
[[[17 14 28]
  [40 42 26]
  [35 42 13]]

 [[14 28 18]
  [42 26 10]
  [42 13 23]]

 [[28 18 44]
  [26 10 25]
  [13 23 18]]

 [[18 44 32]
  [10 25 19]
  [23 18 41]]

 [[44 32 33]
  [25 19 17]
  [18 41 23]]

 [[32 33 11]
  [19 17 37]
  [41 23 18]]

 [[33 11 43]
  [17 37 41]
  [23 18 37]]

 [[11 43 49]
  [37 41 33]
  [18 37 39]]

 [[40 42 26]
  [35 42 13]
  [43 44 42]]

 [[42 26 10]
  [42 13 23]
  [44 42 34]]

 [[26 10 25]
  [13 23 18]
  [42 34 27]]

 [[10 25 19]
  [23 18 41]
  [34 27 17]]

 [[25 19 17]
  [18 41 23]
  [27 17 47]]

 [[19 17 37]
  [41 23 18]
  [17 47 11]]

 [[17 37 41]
  [23 18 37]
  [47 11 17]]

 [[37 41 33]
  [18 37 39]
  [11 17 13]]

 [[35 42 13]


#<u>**Problem 4**</u>

### Write a function which finds the nearest value from a given value in an array of random N elements. Suppose you created an 1-D array with 15 elements taking values between 10 and 500. Your function would take any input from these values and return the nearest value. (You can use np.abs() function)

In [ ]:
random = np.array(np.random.randint(10,500,15))
random

array([316, 126, 346, 392, 168, 295,  32, 337, 495, 448, 466, 367, 471,
        47, 236])

In [ ]:
random[0]

118

In [ ]:
bbb=np.where(random==346)
bbb

(array([2]),)

In [ ]:
list(np.where(random==346))-1

TypeError: ignored

In [ ]:
# Your function below
def nearest_value(inp_value):
  # rrr=list(random)
  # lll=[]
  # for i in rrr:
  #   if i==inp_value:
  #     lll.append((rrr.index(i))-1)
  # return print(random[lll])
  rrr=random
  lll=[]-1
  for i in rrr:
    if i==inp_value:
      lll.append(np.where(rrr==i))
  return print(random[lll])




In [ ]:
nearest_value(236)

TypeError: ignored